name: deploy-interview

on:
  push:
    branches:
      - main
    paths:
      - 'services/Interview/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v2
     - run: cd services/Interview && docker build -t sreerago/interview .
     - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
       env:
         DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
         DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
     - run: docker push sreerago/interview
     - uses: digitalocean/action-doctl@v2
       with:
         token: ${{ secrets.DO_ACCESS_TOKEN }}
     - run: doctl kubernetes cluster kubeconfig save sellskill-4
     - run: kubectl rollout restart deployment interview-depl
